# Generated by Django 4.0.5 on 2022-10-03 03:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=200, unique=True, verbose_name='Complaint Type')),
                ('creation_date', models.DateField(default=datetime.datetime(2022, 10, 3, 3, 25, 45, 369447, tzinfo=utc), verbose_name='Created')),
                ('updation_date', models.DateField(default=datetime.datetime(2022, 10, 3, 3, 25, 45, 369447, tzinfo=utc), verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='Admin Username')),
                ('password', models.CharField(max_length=250, verbose_name='Admin Password')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_mobile',
            field=models.IntegerField(default=3, max_length=11, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 3, 25, 45, 369447, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_fname',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='TbleComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_addr', models.CharField(max_length=250, verbose_name='Complaint Address')),
                ('complaint_details', models.CharField(max_length=250, verbose_name='Complaint Details')),
                ('complaint_file', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'png', 'jpg', 'jpeg'])], verbose_name='Complaint Files')),
                ('complaint_regDate', models.DateField(default=datetime.datetime(2022, 10, 3, 3, 25, 45, 369447, tzinfo=utc), verbose_name='Complaint Submitted Date')),
                ('complaintType', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.complainttype', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250, verbose_name='Complaint Status')),
                ('remark', models.TextField(max_length=250, verbose_name='Remarks')),
                ('remark_date', models.DateField(default=datetime.datetime(2022, 10, 3, 3, 25, 45, 369447, tzinfo=utc), verbose_name='Remark Date')),
                ('tableComplaint', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='users.tblecomplaint')),
            ],
            options={
                'ordering': ['remark_date'],
            },
        ),
    ]
