# Generated by Django 4.0.5 on 2022-10-03 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_complaintremark_remark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 5, 30, 48, 376611, tzinfo=utc), verbose_name='Remark Date'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='complaint_type',
            field=models.CharField(error_messages={'unique': 'Complaint Type already exists'}, max_length=200, unique=True, verbose_name='Complaint Type'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 5, 30, 48, 376611, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 5, 30, 48, 376611, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 5, 30, 48, 376611, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 5, 30, 48, 376611, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
