# Generated by Django 4.0.5 on 2022-10-05 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_complaintremark_remark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 5, 42, 16, 326376, tzinfo=utc), verbose_name='Remark Date'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 5, 42, 16, 326376, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 5, 42, 16, 326376, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 5, 42, 16, 326376, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.IntegerField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 5, 42, 16, 326376, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
