# Generated by Django 4.0.5 on 2022-10-05 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_complaintremark_remark_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='user_fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='user_mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regDate',
        ),
        migrations.AddField(
            model_name='user',
            name='user_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 10, 57, 25, 444229, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='complaintremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 10, 57, 25, 444229, tzinfo=utc), verbose_name='Remark Date'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 10, 57, 25, 444229, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 10, 57, 25, 444229, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 5, 10, 57, 25, 444229, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
    ]
