# Generated by Django 4.0.5 on 2022-10-08 02:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tblecomplaint_complainant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_status', models.CharField(max_length=200, unique=True, verbose_name='status')),
            ],
        ),
        migrations.AlterModelOptions(
            name='complaintremark',
            options={},
        ),
        migrations.RemoveField(
            model_name='complaintremark',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='complaintremark',
            name='status',
        ),
        migrations.RemoveField(
            model_name='complaintremark',
            name='tableComplaint',
        ),
        migrations.AddField(
            model_name='complaintremark',
            name='complaint_remark',
            field=models.CharField(default=1, max_length=1000, verbose_name='remark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblecomplaint',
            name='complaintRemark',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Remark', to='users.complaintremark'),
        ),
        migrations.AlterField(
            model_name='complaintremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 39, 36, 73663, tzinfo=utc), verbose_name='Remark Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 39, 36, 73663, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 39, 36, 73663, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 39, 36, 73663, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 39, 36, 73663, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AddField(
            model_name='tblecomplaint',
            name='complaintStatus',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='users.complaintstatus'),
        ),
    ]
