# Generated by Django 4.0.5 on 2022-10-08 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_tblecomplaint_complaintremark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='complaint_status',
            field=models.CharField(max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='complaint_type',
            field=models.CharField(max_length=200, verbose_name='Complaint Type'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 23, 27, 31, 491311, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 23, 27, 31, 491311, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 23, 27, 31, 491311, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 23, 27, 31, 491311, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
