# Generated by Django 4.0.5 on 2022-10-11 05:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_complainttype_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 5, 23, 31, 586529, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 5, 23, 31, 586529, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaintStatus',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='users.complaintstatus'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_file',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'png', 'jpg', 'jpeg', 'mp4', 'mkv', 'mp3', 'ppt'])], verbose_name='Complaint Files'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 5, 23, 31, 586529, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
    ]
