# Generated by Django 4.0.5 on 2022-10-11 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_complainttype_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 6, 6, 6, 55345, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 6, 6, 6, 55345, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaintStatus',
            field=models.CharField(max_length=20, verbose_name='Complaint Status'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 6, 6, 6, 55345, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
        migrations.DeleteModel(
            name='ComplaintStatus',
        ),
    ]
